### PR TITLE
Improve error handling

### PR DESCRIPTION
**Pull request by patman15**
This is again a bigger change in the code adding better error handling, persistent notification in case of a failure, and an event is fired at the end of each run to allow custom automations. Please see the individual commits for details.
Note: rclone has not been tested!

### CODE REVIEW

**Comment by ikifar2012** [comment]
looks awesome although I would like to keep documentation as part of the documentation website, if you could move that over [here](https://github.com/ikifar2012/addons.mathesonsteplock.ca) that would be great

**Comment by patman15** [comment]
> looks awesome although I would like to keep documentation as part of the documentation website

Sure, I can do so. Should I just create a separate PR against the documentation or how is this handled? I wonder how documentation and code are kept synchronous as there are significant changes that are not backwards compatible.
Do you want to have it
- exclusively [there](https://github.com/ikifar2012/addons.mathesonsteplock.ca) or 
- on both or
- could we at least keep the security hints in the local version?

**Comment by ikifar2012** [comment]
The reason I originally decided to keep documentation exclusively on a separate webpage was for ease of updating without having to change publish a new addon release as I am using the [repository updater](https://github.com/hassio-addons/repository-updater) to manage files in the main ha-addons repo. I think for now we should just keep everything on the site, The website is entirely markdown based and a preview link will be generated on your PR so you can view your changes

**Comment by patman15** [comment]
I created another [PR](https://github.com/ikifar2012/remote-backup-addon/pull/60) and one for the documentation as requested for all of the open PRs.

**Pull request merged**
